---
 - hosts: all-nodes
   become: true
   tasks:

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Add Docker Repository (yum)
      ansible.builtin.yum_repository:
        name: docker-ce
        description: docker official repository
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        enabled: true
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Update Repository Index
      ansible.builtin.yum:
        update_cache: yes

    - name: Installing Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
#This file causes an issue when initializing kubeadm
    - name: Remove containerd toml
      ansible.builtin.file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Enabling Docker Service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Enabling Container Service
      ansible.builtin.systemd:
        name: containerd
        enabled: true
        state: started